### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'form_size'

### ISSUE THREAD

**Issue by rowend** [primal100/django_nosql#1]
# Issue with migration field

## Setup

* __OS:__ Sierra 10.12
* __Python:__ 2.7.10
* __Django:__ 1.9.9
* __Your lib with pip:__ 
```
https://github.com/primal100/django_postgres_extensions/archive/master.zip#egg=django_postgres_extensions==0.9
```

## Model

```python
from django_postgres_extensions.models import ArrayField as DJPEArrayField


class MyModel(models.Model):
  tags = DJPEArrayField(models.CharField(max_length=24), null=True, blank=True)
``` 

## Creating the migration (there is no problem here)

```python
operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('tags', django_postgres_extensions.models.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, form_size=None, null=True, size=None)),
            ],
        ),
    ]
```

## Error running the migration

```python
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/rowend/Projects/buckets/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/rowend/Projects/buckets/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/rowend/Projects/buckets/venv/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/rowend/Projects/buckets/venv/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/rowend/Projects/buckets/venv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 89, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/Users/rowend/Projects/buckets/venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/rowend/Projects/buckets/venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/Users/rowend/Projects/buckets/venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 170, in build_graph
    self.load_disk()
  File "/Users/rowend/Projects/buckets/venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 105, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/rowend/Projects/buckets/bucketspm/main/migrations/0087_mymodel.py", line 13, in <module>
    class Migration(migrations.Migration):
  File "/Users/rowend/Projects/buckets/bucketspm/main/migrations/0087_mymodel.py", line 28, in Migration
    ('tags', django_postgres_extensions.models.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, form_size=None, null=True, size=None)),
  File "/Users/rowend/Projects/buckets/venv/lib/python2.7/site-packages/django/contrib/postgres/fields/array.py", line 30, in __init__
    super(ArrayField, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'form_size'
```

## Solution

* __my temporal solution__: remove the argument __form_size__ from the migration file
```python
('tags', django_postgres_extensions.models.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True,  null=True, size=None)),
```

**Comment by primal100** [comment]
For some reason, the migrate script is calling the normal django.contrib.postgres ArrayField instead of the Postgres Extensions ArrayField, which is why it's rejecting the form size kwarg. It works when the test suite makes migrations but not with a normal app. 

I fixed it by removing "from fields import *" from the models __init__.py file. Now it is required to import the fields directly as

```python
 from django_postgres_extensions.models.fields import ArrayField
```

I've updated the readme. Not sure why it didn't work before though.

**Comment by andres-torres-marroquin** [comment]
Investigating this issue I found out this:
```bash
$ python manage.py shell
Python 3.6.3 (default, Oct  4 2017, 06:09:15)
Type "copyright", "credits" or "license" for more information.

IPython 1.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import django_postgres_extensions.models.fields

In [2]: print(django_postgres_extensions.models.fields)
<module 'django.contrib.postgres.fields' from '/Users/andres/Projects/buckets/venv/lib/python3.6/site-packages/django/contrib/postgres/fields/__init__.py'>
```

It seems that importing `django_postgres_extensions.models.fields`, imports an unexpected file.
I also found out that if you modify the import the first import in the file `django_postgres_extensions/models/fields/__init__.py` from:
`from django.contrib.postgres import fields`
to:
`from django.contrib.postgres import fields as django_fields`
Also don't forgetting to change all the references too.
